AWSTemplateFormatVersion: "2010-09-09"
Description: Create cross account role for service screener
Parameters:
  RoleName:
    Type: String
    Default: ServiceScreenerAssumeRole
  ExecAccountNo:
    Type: String
Resources:
  SSRole: #An inline comment
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              AWS: 
                - !Sub 'arn:aws:iam::${ExecAccountNo}:root'
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      Policies:
        - PolicyName: CloudFormationCreateStack
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'cloudformation:CreateStack'
                Resource: '*'