name: Build Docker Base Image for Screener Scheduler
on:
  push:
    branches:
      - ugym-automation
      - main
jobs:
    build:
      name: push docker base image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build ./usecases/scheduler/docker/docker-base-image -t yingtingaws/screener-scheduler-base:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_USERNAME}}/screener-scheduler-base:latest