name: Validate Reporter Files

on:
  pull_request:
    paths:
      - 'services/**/*.reporter.json'
  push:
    paths:
      - 'services/**/*.reporter.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run validation
        run: python scripts/validate_reporter.py

      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const output = require('${{ github.workspace }}/validation-output.json');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Reporter file validation failed:\n\n${output.errors.join('\n')}`
            });
